---
title: "30 Day Map Challenge - Ecoinformática AEET"
author: "Julia G. de Aledo"
date: "2025-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 30 Day Map Challenge - 28_Black

### Day callenge description

(Black Friday) Interpret the theme of Black. The map can be purely monochromatic, represent absence/darkness (e.g., light pollution), or relate to themes of consumption.

### Something about the map!

The position of 233309 night street lamps of Madrid.

```{r create_map}

library(sf)
library(ggplot2)

farolas <- read_sf('2025_30DayMapChallenge_files/28_Black/20220408_DATOS_ABIERTOS_UNIDAD_LUMINOSA_/20220408_DATOS_ABIERTOS_UNIDAD_LUMINOSA_.shp')
farolas = farolas$geometry
p1 = ggplot(farolas) + geom_sf(
  col = "yellow",
  size = .1,
  shape = 16,
  alpha = .1) + theme_void() +
  theme(plot.background = element_rect(fill = "black"))
p1
#ggsave("2025_30DayMapChallenge_files/28_Black/farolas.png", p1, width=10, height=10)

```


